init package
fishaudio/fish-speech pull request #138
Opened 2024-04-27 11:20 UTC by AnyaCoder

**Is this PR adding new feature or fix a BUG?**

Add feature.

**Is this pull request related to any issue? If yes, please link the issue.**

Initial Version of Package.

2024-04-27 12:16 UTC, leng-yue requested changes
Nice job overall!

2024-04-27 12:16 UTC, leng-yue commented on fish_speech/datasets/text.py
Why we need to replace mask our with text-labeler?

2024-04-27 12:16 UTC, leng-yue commented on fish_speech/train.py
This should be override in launching script: `trainer.strategy.process_group_backend=gloo`

2024-04-27 12:16 UTC, leng-yue commented on tools/webui.py
should try import spaces, this is important for huggingface spaces.

```python
try:
    import spaces
    GPU_DECORATOR = spaces.GPU
except ImportError:
    def GPU_DECORATOR(func):
        def wrapper(*args, **kwargs):
            return func(*args, **kwargs)
        return wrapper
```

2024-04-27 12:26 UTC, AnyaCoder commented on fish_speech/datasets/text.py
Ahh, thanks to pycharm's renaming

2024-04-27 12:26 UTC, AnyaCoder commented on fish_speech/datasets/text.py
Ahh, thanks to pycharm's renaming

2024-04-27 12:44 UTC, AnyaCoder commented on tools/webui.py
ok

2024-04-27 13:13 UTC, AnyaCoder commented on fish_speech/train.py
![image](https://github.com/fishaudio/fish-speech/assets/122108331/90f26aeb-2391-4605-ba83-a4db67cbe659)
![image](https://github.com/fishaudio/fish-speech/assets/122108331/06a6d93d-9c89-4f5f-88fe-33015ad4b98d)
Seems not okay...

2024-04-27 13:52 UTC, AnyaCoder commented on fish_speech/train.py
OK，I‘ve resolved the problem by adding some params in `yaml`

2024-04-28 02:18 UTC, leng-yue approved these changes

2024-04-28 02:18 UTC, merged